version: '3'
services:
  jagaad_application:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jagaad_application
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  main-db-data:
    driver: local
